### PR TITLE
add Swift 2.0 and Xcode 7 support

### PR DESCRIPTION
**Pull request by sync**
see #20

### CODE REVIEW

**Comment by sync** [comment]
i'll work on the fallible initialiser soonish

**Comment by pfitz** [comment]
Any updates on this PR? Can one use Xcode 7 Beta with travis?

**Comment by sync** [comment]
I've decided to settle with a init method that throws, see  4fdf5d9.

**Comment by sync** [comment]
it's not possible to use Xcode 7 Beta with travis

**Comment by pfitz** [comment]
Nice implementation. :+1:  Would love to see this pull request merged.

**Comment by aschuch** [comment]
> I've decided to settle with a init method that throws, see 4fdf5d9, would love to get feedback from this idea

I am really not sure if we should settle with this approach. I know I initially said that a failable initializer would be fine, but seeing the actual sample code, it seems like this creates an unnecessary burden for the user. In the end, what can one do if the directory cannot be created?

**Comment by sync** [comment]
Sorry for the late reply, I totally agree it's not so good

**Comment by sync** [comment]
perhaps this article would help decide: http://owensd.io/2015/07/07/failable-init-vs-throws.html

**Comment by aschuch** [comment]
@sync, thanks for all the work you already put into this.
Reading through your article and thinking about it again, I guess a trowing initializer is fine, since the consumer has `guard` and `try?` to make sure the cache is actually present.

Would you mind updating travis to `xcode7`, so we can run all tests on this PR?

**Comment by sync** [comment]
not a problem, I won't be able to do this right away. If it's urgent, feel free to reuse  or modify any of the code from this PR, also if more convenient you can close this PR.

It seems that since GM there is a bunch of string + directory related deprecated methods. I reckon changing

`public let cacheDirectory: String` to `public let cacheDirectory: NSURL` would perhaps help getting ride of these deprecations errors.

**Comment by aschuch** [comment]
Ok, thanks I'll give it a shot probably.

**Pull request closed without merging**
