### PR TITLE
add Swift 2.0 and Xcode 7 support

### PR DESCRIPTION
**Pull request by sync**
not sure if you want to add this to master or not, errors coming from `try` are essentially ignored

### CODE REVIEW

**Comment by aschuch** [comment]
Thanks for the PR.
I am not sure if errors should just be `catch`ed by AwesomeCache or if we should add `throws` to all methods that interact with the file system.

Any opinions?

**Comment by sync** [comment]
I think out of the 5 `catch` added, the only one that really isn't internal logic is the one inside, `public init(name: String, directory: String?)`

perhaps both `public init` methods should be fallible initialiser if an exception is thrown ?

if we add throws to all methods that interact with the file system, can the user really recover from an error being thrown ? I don't think so

**Comment by aschuch** [comment]
Yes, adding failable initializers would be appropriate I think. The cache did not expose any failures that have to do with the file system until now, and that seemed to work fine anyways.

Do you want to make the changes?
I would like to keep swift 2.0 support on a separate branch until it is final in fall.

**Comment by sync** [comment]
i'll make the change

**Comment by sync** [comment]
if you create a swift 2.0 branch on your repo even if blank I can send a PR from this branch into your swift 2.0 branch

**Comment by aschuch** [comment]
Cool, I've created a `swift-2.0` branch for you.

**Comment by sync** [comment]
will send same PR against swift-2.0 branch

**Pull request closed without merging**
